import os
import datetime
import json

# --- PATHS ---
AUDIT_DIR = "D:/audits"
DASHBOARD_PATH = "D:/audits/SOVEREIGN_FORENSIC_DASHBOARD.html"

def generate_dashboard():
    # 1. Gather Metrics
    files = os.listdir(AUDIT_DIR)
    evidence_files = [f for f in files if f.endswith(".md") or f.endswith(".txt")]
    images = [f for f in files if f.endswith(".png") or f.endswith(".jpeg") or f.endswith(".PNG")]
    
    # 2. Check Perimeter
    hosts_file = r"C:\Windows\System32\drivers\etc\hosts"
    sealed = False
    try:
        with open(hosts_file, "r") as f:
            content = f.read()
            if "phoenix-gw.alibaba.com" in content:
                sealed = True
    except:
        pass

    # 3. HTML Template
    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Sovereign Forensic Dashboard | Canon 8.11</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            body {{ background-color: #010409; color: #e6edf3; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }}
            .card {{ background-color: #0d1117; border: 1px solid #30363d; border-radius: 8px; padding: 20px; }}
            .status-ok {{ color: #3fb950; }}
            .status-fail {{ color: #f85149; }}
        </style>
    </head>
    <body class="p-8">
        <div class="max-w-6xl mx-auto">
            <header class="mb-8 border-b border-zinc-800 pb-4">
                <h1 class="text-3xl font-bold">SOVEREIGN FORENSIC DASHBOARD</h1>
                <p class="text-zinc-500 uppercase tracking-widest text-xs mt-2">Status: VERIFIED TRUTH // Protocol: CANON 8.11</p>
            </header>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                <div class="card">
                    <h3 class="text-zinc-500 text-xs font-bold uppercase mb-2">Perimeter Integrity</h3>
                    <p class="text-2xl font-bold {'status-ok' if sealed else 'status-fail'}">
                        {'SEALED' if sealed else 'UNSECURED'}
                    </p>
                </div>
                <div class="card">
                    <h3 class="text-zinc-500 text-xs font-bold uppercase mb-2">Evidence Anchors</h3>
                    <p class="text-2xl font-bold">{len(evidence_files)} Verified Files</p>
                </div>
                <div class="card">
                    <h3 class="text-zinc-500 text-xs font-bold uppercase mb-2">Visual Evidence</h3>
                    <p class="text-2xl font-bold">{len(images)} Snapshots</p>
                </div>
            </div>

            <div class="card mb-8">
                <h2 class="text-xl font-bold mb-4">Master Evidence Chain (D:/audits)</h2>
                <ul class="space-y-2 text-sm">
                    {"".join([f'<li><span class="text-blue-400">📄</span> {f}</li>' for f in evidence_files[:15]])}
                    <li class="text-zinc-500 italic">... and {len(evidence_files)-15 if len(evidence_files)>15 else 0} more</li>
                </ul>
            </div>

            <footer class="text-center text-zinc-600 text-[10px] mt-12 uppercase tracking-[0.5em]">
                Generated by Sovereign Brain Core // {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </footer>
        </div>
    </body>
    </html>
    """
    
    with open(DASHBOARD_PATH, "w", encoding="utf-8") as f:
        f.write(html)
    return f"Dashboard generated at {DASHBOARD_PATH}"

if __name__ == "__main__":
    print(generate_dashboard())
