import json
import os
import sqlite3
from datetime import datetime

# CONFIGURATION
EXTRACTS_DIR = r"C:\audits\extracts"
GH_REPO = "chippychris844-star/sovereign-audit-ledger"
FRICTION_THRESHOLD = 0.8

def create_gh_issue(title, body):
    print(f"Creating GitHub Issue: {title}")
    # Using gh CLI via os.system
    cmd = f'gh issue create --repo {GH_REPO} --title "{title}" --body "{body}"'
    os.system(cmd)

def scan_for_leads():
    print("Scanning for Forensic Leads...")
    if not os.path.exists(EXTRACTS_DIR):
        return
        
    files = [f for f in os.listdir(EXTRACTS_DIR) if f.endswith('.json')]
    
    for f in files:
        path = os.path.join(EXTRACTS_DIR, f)
        with open(path, 'r', encoding='utf-8-sig') as jf:
            try:
                content = jf.read()
                if not content.strip():
                    continue
                data_list = json.loads(content)
                if not isinstance(data_list, list):
                    data_list = [data_list]
                
                for data in data_list:
                    # Check for high friction score
                    friction = data.get("friction_score", 0)
                    if friction >= FRICTION_THRESHOLD:
                        title = f"[FORENSIC LEAD] High Friction Detected in {data.get('source', 'Unknown')}"
                        body = f"Signal ID: {data.get('capture_id', 'N/A')}\nTimestamp: {data.get('timestamp_utc', 'N/A')}\nFriction Score: {friction}\nSummary: {data.get('summary', 'N/A')}\n\nAutomated lead generated by Sovereign Forensic Engine."
                        create_gh_issue(title, body)
                    
                    # Check for specific high-risk signals (e.g., BGP leaks)
                    if "bgp" in f.lower() or "leak" in str(data).lower():
                        title = f"[FORENSIC LEAD] Network Anomaly Detected"
                        body = f"Potential BGP leak or network anomaly found in {f}.\n\nSignal Data:\n{json.dumps(data, indent=2)}"
                        create_gh_issue(title, body)
            except Exception as e:
                print(f"Error processing {f}: {e}")

if __name__ == "__main__":
    scan_for_leads()
